# Generated by Django 5.0.7 on 2025-03-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0007_resource'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='faq',
        #     options={'ordering': ['order']},
        # ),
        # migrations.AddField(
        #     model_name='faq',
        #     name='order',
        #     field=models.IntegerField(default=0),
        # ),
        migrations.AlterField(
            model_name='resource',
            name='state_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='communityEmpowerment.state'),
        ),
    ]
