# Generated by Django 5.0.7 on 2025-03-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0008_alter_faq_options_faq_order_and_more'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='faq',
        #     options={'ordering': ['order']},
        # ),
        # migrations.AddField(
        #     model_name='faq',
        #     name='order',
        #     field=models.IntegerField(default=0),
        # ),
        migrations.AddField(
            model_name='profilefield',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]