# Generated by Django 5.0.7 on 2025-03-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0009_alter_faq_options_faq_order_profilefield_is_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        # migrations.AlterModelOptions(
        #     name='faq',
        #     options={'ordering': ['order']},
        # ),
        # migrations.AddField(
        #     model_name='faq',
        #     name='order',
        #     field=models.IntegerField(default=0),
        # ),
    ]
