# Generated by Django 5.0.7 on 2025-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0010_announcement_alter_faq_options_faq_order'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='faq',
        #     options={'ordering': ['order']},
        # ),
        # migrations.AddField(
        #     model_name='faq',
        #     name='order',
        #     field=models.IntegerField(default=0),
        # ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('scholarship', 'Scholarship'), ('job', 'Job Opening'), ('govt_job', 'Government Job'), ('private_job', 'Private Job'), ('internship', 'Internship'), ('skill_based_job', 'Skill-Based Job'), ('defense_job', 'Defense & Police Job'), ('sc', 'Scheduled Caste (SC)'), ('st', 'Scheduled Tribe (ST)'), ('obc', 'Other Backward Classes (OBC)'), ('minority', 'Minority Community'), ('general', 'General'), ('financial_assistance', 'Financial Assistance & Subsidies'), ('women', 'Women-Centric Schemes'), ('agriculture', 'Agriculture & Farmers'), ('senior_citizen', 'Senior Citizens & Pension'), ('disability', 'Disability & Special Needs'), ('business', 'Startups & Business Development'), ('education', 'Education & Training'), ('health', 'Health & Insurance'), ('housing', 'Housing & Infrastructure'), ('youth_skill', 'Youth & Skill Development'), ('state_specific', 'State-Specific Schemes')], default='general', max_length=50),
        ),
    ]
