# Generated by Django 5.0.7 on 2025-04-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0011_alter_faq_options_faq_order_alter_tag_category'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='faq',
        #     options={'ordering': ['order']},
        # ),
        migrations.RemoveField(
            model_name='userevents',
            name='scheme_id',
        ),
        # migrations.AddField(
        #     model_name='faq',
        #     name='order',
        #     field=models.IntegerField(default=0),
        # ),
        migrations.AddField(
            model_name='userevents',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.scheme'),
        ),
    ]
