# Generated by Django 5.0.7 on 2025-04-07 07:04

import communityEmpowerment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0012_alter_faq_options_remove_userevents_scheme_id_and_more'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='faq',
        #     options={'ordering': ['order']},
        # ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='banners/default.jpg', storage=communityEmpowerment.models.MediaStorage(), upload_to='announcements/'),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='faq',
        #     name='order',
        #     field=models.IntegerField(default=0),
        # ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
