# Generated by Django 5.0.7 on 2025-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0013_alter_faq_options_announcement_image_faq_order_and_more'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='faq',
        #     options={'ordering': ['order']},
        # ),
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.AddField(
            model_name='announcement',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='view_link',
            field=models.URLField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='faq',
        #     name='order',
        #     field=models.IntegerField(default=0),
        # ),
    ]
