# Generated by Django 4.2.20 on 2025-04-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0017_alter_faq_options_faq_order_state_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='resource',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='schemefeedback',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='schemereport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='websitefeedback',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
    ]
