# Generated by Django 4.2.20 on 2025-04-29 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0018_alter_faq_options_announcement_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemebeneficiary',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
        migrations.AddField(
            model_name='schemesponsor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
    ]
