# Generated by Django 4.2.20 on 2025-04-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0019_alter_faq_options_faq_order_faq_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
    ]
