# Generated by Django 4.2.20 on 2025-05-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0020_alter_faq_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
    ]
