# Generated by Django 4.2.20 on 2025-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0022_alter_faq_options_faq_order_userprivacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivacysettings',
            name='allow_cookies_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
