# Generated by Django 4.2.20 on 2025-05-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0023_alter_faq_options_faq_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevents',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communityEmpowerment.organization'),
        ),
    ]
