# Generated by Django 4.2.20 on 2025-05-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0024_alter_faq_options_faq_order_userevents_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingSchemeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255)),
                ('scheme_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='missing_scheme_docs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
