# Generated by Django 4.2.20 on 2025-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityEmpowerment', '0025_missingschemereport_alter_faq_options_faq_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemereport',
            name='report_category',
            field=models.CharField(choices=[('incorrect_info', 'Incorrect Information'), ('outdated_info', 'Outdated Information'), ('broken_link', 'Broken Link'), ('language_issue', 'Language Issue'), ('irrelevant', 'Irrelevant'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='websitefeedback',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('improvement', 'Improvement Suggestion'), ('ui', 'User Interface'), ('performance', 'Performance'), ('content', 'Content'), ('other', 'Other'), ('general', 'General Feedback')], max_length=50),
        ),
    ]
